- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init  >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install the Tigera Calico operator and custom resource definitions
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
    
    - name: Install Calico by creating the necessary custom resource #https://docs.projectcalico.org/getting-started/kubernetes/quickstart
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f kubectl create -f kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
