- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - debug:
        msg: "{{ join_command }}"  

- hosts: workers
  become: yes
  tasks:
    - set_fact:
        kubeadmjoin: |
                     {% for host in groups['master'] %}
                      {{ hostvars[host].join_command }}
                      {% endfor %}
    - debug:
        msg: "{{  kubeadmjoin | trim }} "  
    - name: join cluster
      become: yes
      shell: "{{ kubeadmjoin | trim }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
